-   id: flakeheaven
    name: flakeheaven
    description: '`flakeheaven` is a `flake8` wrapper to make a nice, legacy-friendly, configurable command-line utility for enforcing style consistency across Python projects.'
    entry: flakeheaven lint
    language: python
    types: [file, text]
    files: \.(ipynb|md|py|rst|yaml|yml)$
    require_serial: true
