name: Upload Python Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel poetry
        pip --version
        wheel version
        poetry --version

    - name: Publish
      run: |
        ./scripts/publish \
        && export INCOMING_TAG=$(poetry version --short) \
        && echo "INCOMING_TAG=${INCOMING_TAG}" >> "$GITHUB_ENV"

      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    - name: Upload Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'dist/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ env.INCOMING_TAG }}
